# This is a basic workflow to help you get started with Actions

name: RUN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run Windows95
        run: |
          tar xf windows.tar.gz
          sudo apt update
          sudo apt install qemu-system-x86 snap snapd -y
          sudo snap install novnc
          novnc --listen 6081 --vnc localhost:5901 & sudo qemu-system-x86_64 -m 128 -hda windows95.img -netdev user,id=mynet0 -device ne2k_isa,netdev=mynet0 -vnc 6081
          
